In [109]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt 
import numpy as np 
from sklearn import datasets, linear_model, metrics 
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
import numpy as np
from math import sqrt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score as acc
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
from sklearn.linear_model import Lasso 
from sklearn.pipeline import Pipeline
import xgboost as xgb
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV

In [135]:
df = pd.read_csv("C:/Users/USER/Downloads/big_train.csv")
test = pd.read_csv("C:/Users/USER/Downloads/big_test.csv")

df_X = df.drop(['reg','Outlet_Establishment_Year'],axis=1)
df_Y = df['Item_Outlet_Sales']

test_X = test.drop(['reg','Outlet_Establishment_Year'],axis=1)
#test_Y = test['Item_Outlet_Sales']

In [136]:
df_X['Unnamed: 0']
test_X['Unnamed: 0']

0          0
1          1
2          2
3          3
4          4
        ...
5676    5676
5677    5677
5678    5678
5679    5679
5680    5680
Name: Unnamed: 0, Length: 5681, dtype: int64

In [137]:
df_X

,Unnamed: 0,Item_Identifier,Item_Weight,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,low_fat
0,0,FDA15,9.300,0.016047,Dairy,249.8092,OUT049,Medium,Tier 1,Supermarket Type1,3735.1380,1
1,1,DRC01,5.920,0.019278,Soft Drinks,48.2692,OUT018,Medium,Tier 3,Supermarket Type2,443.4228,0
2,2,FDN15,17.500,0.016760,Meat,141.6180,OUT049,Medium,Tier 1,Supermarket Type1,2097.2700,1
3,3,FDX07,19.200,0.000000,Fruits and Vegetables,182.0950,OUT010,NaN,Tier 3,Grocery Store,732.3800,0
4,4,NCD19,8.930,0.000000,Household,53.8614,OUT013,High,Tier 3,Supermarket Type1,994.7052,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,8518,FDF22,6.865,0.056783,Snack Foods,214.5218,OUT013,High,Tier 3,Supermarket Type1,2778.3834,1
8519,8519,FDS36,8.380,0.046982,Baking Goods,108.1570,OUT045,NaN,Tier 2,Supermarket Type1,549.2850,0
8520,8520,NCJ29,10.600,0.035186,Health and Hygiene,85.1224,OUT035,Small,Tier 2,Supermarket Type1,1193.1136,1
8521,8521,FDN46,7.210,0.145221,Snack Foods,103.1332,OUT018,Medium,Tier 3,Supermarket Type2,1845.5976,0
8522,8522,DRG01,14.800,0.044878,Soft Drinks,75.4670,OUT046,Small,Tier 1,Supermarket Type1,765.6700,1

In [138]:
number = LabelEncoder()
df_X['Item_Type'] = number.fit_transform(df_X['Item_Type'].astype(str))
#df_X['Outlet_Establishment_Year'] = number.fit_transform(df_X['Outlet_Establishment_Year'].astype(str))
df_X['Outlet_Size'] = number.fit_transform(df_X['Outlet_Size'].astype(str))
df_X['Outlet_Location_Type'] = number.fit_transform(df_X['Outlet_Location_Type'].astype(str))
df_X['Outlet_Type'] = number.fit_transform(df_X['Outlet_Type'].astype(str))
df_X['Outlet_Identifier'] = number.fit_transform(df_X['Outlet_Identifier'].astype(str))
#df_X['Item_Identifier'] = number.fit_transform(df_X['Item_Identifier'].astype(str))
#df_X['Item_Identifier'] = number.fit_transform(df_X['Item_Identifier'].astype(str))

number = LabelEncoder()
test_X['Item_Type'] = number.fit_transform(test_X['Item_Type'].astype(str))
#test_X['Outlet_Establishment_Year'] = number.fit_transform(test_X['Outlet_Establishment_Year'].astype(str))
test_X['Outlet_Size'] = number.fit_transform(test_X['Outlet_Size'].astype(str))
test_X['Outlet_Location_Type'] = number.fit_transform(test_X['Outlet_Location_Type'].astype(str))
test_X['Outlet_Type'] = number.fit_transform(test_X['Outlet_Type'].astype(str))
test_X['Outlet_Identifier'] = number.fit_transform(test_X['Outlet_Identifier'].astype(str))
#test_X['Item_Identifier'] = number.fit_transform(test_X['Item_Identifier'].astype(str))
#test_X['Item_Identifier'] = number.fit_transform(test_X['Item_Identifier'].astype(str))

In [139]:
df['Outlet_Size'].replace(3, 0, inplace=True)

test['Outlet_Size'].replace(3, 0, inplace=True)

In [140]:
median = df_X['Outlet_Size'].mode()
df_X['Outlet_Size'].fillna(median, inplace=True)

median = test_X['Outlet_Size'].mode()
test_X['Outlet_Size'].fillna(median, inplace=True)

#mean2 = df_X['Item_Weight'].mean()
#df_X['Item_Weight'].fillna(mean2, inplace=True)

#mean1 = test_X['Item_Weight'].mean()
#test_X['Item_Weight'].fillna(mean2, inplace=True)

In [141]:
df_X

,Unnamed: 0,Item_Identifier,Item_Weight,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,low_fat
0,0,FDA15,9.300,0.016047,4,249.8092,9,1,0,1,3735.1380,1
1,1,DRC01,5.920,0.019278,14,48.2692,3,1,2,2,443.4228,0
2,2,FDN15,17.500,0.016760,10,141.6180,9,1,0,1,2097.2700,1
3,3,FDX07,19.200,0.000000,6,182.0950,0,3,2,0,732.3800,0
4,4,NCD19,8.930,0.000000,9,53.8614,1,0,2,1,994.7052,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,8518,FDF22,6.865,0.056783,13,214.5218,1,0,2,1,2778.3834,1
8519,8519,FDS36,8.380,0.046982,0,108.1570,7,3,1,1,549.2850,0
8520,8520,NCJ29,10.600,0.035186,8,85.1224,6,2,1,1,1193.1136,1
8521,8521,FDN46,7.210,0.145221,13,103.1332,3,1,2,2,1845.5976,0
8522,8522,DRG01,14.800,0.044878,14,75.4670,8,2,0,1,765.6700,1

In [142]:

df_X['Item_Identifier'] = df_X['Item_Identifier'].map(df_X['Item_Identifier'].value_counts().to_dict())
test_X['Item_Identifier'] = test_X['Item_Identifier'].map(test_X['Item_Identifier'].value_counts().to_dict())

In [143]:
#y1 = pd.get_dummies(df_X['Outlet_Type'],prefix='Outlet_Type',drop_first=True)

#df_X['Outlet_Type_1'] = y1['Outlet_Type_1']
#df_X['Outlet_Type_2'] = y1['Outlet_Type_2']
#df_X['Outlet_Type_3'] = y1['Outlet_Type_3']


#y2 = pd.get_dummies(test_X['Outlet_Type'],prefix='Outlet_Type',drop_first=True)

#test_X['Outlet_Type_1'] = y2['Outlet_Type_1']
#test_X['Outlet_Type_2'] = y2['Outlet_Type_2']
#test_X['Outlet_Type_3'] = y2['Outlet_Type_3']

In [144]:
df_X

,Unnamed: 0,Item_Identifier,Item_Weight,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,low_fat
0,0,8,9.300,0.016047,4,249.8092,9,1,0,1,3735.1380,1
1,1,6,5.920,0.019278,14,48.2692,3,1,2,2,443.4228,0
2,2,7,17.500,0.016760,10,141.6180,9,1,0,1,2097.2700,1
3,3,6,19.200,0.000000,6,182.0950,0,3,2,0,732.3800,0
4,4,6,8.930,0.000000,9,53.8614,1,0,2,1,994.7052,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,8518,8,6.865,0.056783,13,214.5218,1,0,2,1,2778.3834,1
8519,8519,6,8.380,0.046982,0,108.1570,7,3,1,1,549.2850,0
8520,8520,6,10.600,0.035186,8,85.1224,6,2,1,1,1193.1136,1
8521,8521,6,7.210,0.145221,13,103.1332,3,1,2,2,1845.5976,0
8522,8522,5,14.800,0.044878,14,75.4670,8,2,0,1,765.6700,1

In [145]:
df1 = df_X.groupby('Item_Identifier')['Item_Weight'].mean()
rf1 = pd.merge(df_X,df1,on='Item_Identifier')
rf1.dropna(subset = ["Item_Weight_y"], inplace=True)
df_X = rf1.drop(['Item_Weight_x'],axis=1)

df2 = test_X.groupby('Item_Identifier')['Item_Weight'].mean()
rf2 = pd.merge(test_X,df2,on='Item_Identifier')
rf2.dropna(subset = ["Item_Weight_y"], inplace=True)
test_X = rf2.drop(['Item_Weight_x'],axis=1)

In [146]:
test_X

,Unnamed: 0,Item_Identifier,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,low_fat,Item_Weight_y
0,0,7,0.007565,13,107.8622,9,1,0,1,1,12.160809
1,14,7,0.021206,7,52.0298,1,0,2,1,1,12.160809
2,18,7,0.028184,9,109.6912,5,1,2,3,1,12.160809
3,29,7,0.022940,6,116.5492,6,2,1,1,1,12.160809
4,30,7,0.067377,9,32.0900,4,2,0,0,1,12.160809
...,...,...,...,...,...,...,...,...,...,...,...
5676,5433,8,0.083943,10,257.4330,8,2,0,1,1,11.462193
5677,5535,8,0.109820,0,120.6098,3,1,2,2,0,11.462193
5678,5607,8,0.052094,14,185.4898,2,3,1,1,1,11.462193
5679,5611,8,0.000000,8,182.6608,3,1,2,2,1,11.462193
5680,5635,8,0.000000,8,184.2608,8,2,0,1,1,11.462193

In [147]:
test_X.to_csv('big7.csv')

In [148]:
#df_X.loc[df['Item_Visibility'] <= 0, 'visible'] = 'False' 
#df_X.loc[df['Item_Visibility'] > 0, 'visible'] = 'True' 
#test_X.loc[df['Item_Visibility'] <= 0, 'visible'] = 'False' 
#test_X.loc[df['Item_Visibility'] > 0, 'visible'] = 'True' 

#df_X['visible'] = number.fit_transform(df_X['visible'].astype(str))
#test_X['visible'] = number.fit_transform(test_X['visible'].astype(str))

In [149]:
#frequency = df_X['Item_Type'].value_counts(normalize =True)


#mapping = df_X['Item_Type'].map(frequency)

#df_X['Item_Type'] = df_X['Item_Type'].mask(mapping < 0.03,'others')

#df_X['Item_Type'] = number.fit_transform(df_X['Item_Type'].astype(str))
#test_X['Item_Type'] = number.fit_transform(test_X['Item_Type'].astype(str))

In [150]:
 print(frequency * 100)

NameError: name 'frequency' is not defined

In [151]:
test_X  = test_X.sort_values(by=['Unnamed: 0'])

In [152]:
test_X

,Unnamed: 0,Item_Identifier,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,low_fat,Item_Weight_y
0,0,7,0.007565,13,107.8622,9,1,0,1,1,12.160809
329,1,6,0.038428,4,87.3198,2,3,1,1,0,12.068420
977,2,4,0.099575,11,241.7538,0,3,2,0,1,12.894117
2625,3,3,0.015388,13,155.0340,2,3,1,1,1,13.123995
978,4,4,0.118599,4,234.2300,5,1,2,3,0,12.894117
...,...,...,...,...,...,...,...,...,...,...,...
3758,5676,3,0.013496,13,141.3154,8,2,0,1,0,13.123995
2623,5677,4,0.142991,15,169.1448,3,1,2,2,0,12.894117
4246,5678,2,0.073529,8,118.7440,7,3,1,1,1,13.251061
5526,5679,5,0.000000,3,214.6218,2,3,1,1,0,12.315441
2624,5680,4,0.104720,3,79.7960,7,3,1,1,0,12.894117

In [153]:
df_Y = df_X['Item_Outlet_Sales']
df_X = df_X.drop(['Item_Outlet_Sales','Unnamed: 0'],axis=1)
test_X = test_X.drop(['Unnamed: 0'],axis=1)

In [154]:


#############################-----TRAIN-----############################
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(df_X, df_Y, test_size=0.3, 
                                                    random_state=1) 
  
# create linear regression object 
reg = linear_model.LinearRegression() 
ran = RandomForestRegressor()
xgr = xgb.XGBRegressor( loss='ls', learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0, min_impurity_split=None, init=None, random_state=None, max_features=None, alpha=0.9, verbose=0, max_leaf_nodes=None, warm_start=False, presort='deprecated', validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)
dec = DecisionTreeRegressor(random_state = 0) 
ada=AdaBoostRegressor()
lasso = Lasso(alpha=1)

In [167]:


param_dist = { "max_depth" :[4,5,7]}
          
              
logreg_cv = GridSearchCV(ran, param_dist,cv = 5) 
  
logreg_cv.fit(df_X, df_Y)             




#xgr = xgb.XGBRegressor(param_dist)
#xgr = xgb.XGBRegressor( loss='ls', learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0, min_impurity_split=None, init=None, random_state=None, max_features=None, alpha=0.9, verbose=0, max_leaf_nodes=None, warm_start=False, presort='deprecated', validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)
#xgr.fit(X_train, y_train) 
#ans1 =  xgr.predict(X_test)
#rmse = np.sqrt(mean_squared_error(y_test, ans1))
#print("RMSE: %f" % (rmse))
print("Tuned Logistic Regression Parameters: {}".format(logreg_cv.best_params_))  
print("Best score is {}".format(logreg_cv.best_score_))

Tuned Logistic Regression Parameters: {'max_depth': 5}
Best score is 0.5969508066294177

In [168]:
ran=RandomForestRegressor(max_depth= 5)
ran.fit(X_train, y_train)
ans1 =  ran.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, ans1))
print("RMSE: %f" % (rmse))

RMSE: 1041.692721

In [169]:


Pipeline_1 = Pipeline([('pca1',reg)])

Pipeline_2 = Pipeline([('pca2',ran)])

Pipeline_3 = Pipeline([('pca3',xgr)])

Pipeline_4 = Pipeline([('pca4',dec)])

Pipeline_5 = Pipeline([('pca5',ada)])

Pipeline_6 = Pipeline([('pca6',lasso)])

pipeline = [Pipeline_1,Pipeline_2,Pipeline_3,Pipeline_4,Pipeline_5,Pipeline_6]

pipe_dict = {0:'Pipeline_1', 1:'e ipeline_2'}

for pipe in pipeline:
    pipe.fit(X_train, y_train)
    ans1 =  pipe.predict(X_test)
    #print(mean_squared_error(y_test, ans1))
    rmse = np.sqrt(mean_squared_error(y_test, ans1))
    print("RMSE: %f" % (rmse))

RMSE: 1180.978609
RMSE: 1040.938984

XGBoostError: Invalid Parameter format for seed expect int but value='None'

In [172]:
kf = KFold(n_splits = 5, shuffle = True)

scores = []
for i in range(5):
    result = next(kf.split(df_X),None)
    x_train = df_X.iloc[result[0]]
    x_test = df_X.iloc[result[1]]
    y_train = df_Y.iloc[result[0]]
    y_test = df_Y.iloc[result[1]]
    lasso.fit(x_train,y_train)
    pred_gb = lasso.predict(x_test)
    rmse = np.sqrt(mean_squared_error(y_test, pred_gb))
    print("RMSE: %f" % (rmse))

RMSE: 1223.304721
RMSE: 1177.505534
RMSE: 1226.909879
RMSE: 1213.442147
RMSE: 1229.070190

In [95]:

ans4 =  lasso.predict(test_X)
ans1 =  ran.predict(test_X)
ans2 =  xgr.predict(test_X)
ans3 =  ada.predict(test_X)
ans5 =  reg.predict(test_X)

In [96]:
any(ans1<0)

False

In [97]:
test_X['ans'] = ans1

In [98]:
test_X['ans']

0       1788.412038
329     1222.894834
977      666.126242
2625    2348.975690
978     6223.652054
           ...
3758    2427.513458
2623    2891.569400
4246    2137.490978
5526    4959.484278
2624    1428.427294
Name: ans, Length: 5681, dtype: float64

In [155]:
test_X.to_csv('big20_ans.csv')

In [72]:
frequency = df['department'].value_counts(normalize =True)

KeyError: 'department'

In [50]:
test_X

,Unnamed: 0,Item_Identifier,Item_Weight,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,low_fat
0,0,FDW58,20.750000,0.007565,13,107.8622,9,1,0,1,1
1,1,FDW14,8.300000,0.038428,4,87.3198,2,3,1,1,0
2,2,NCN55,14.600000,0.099575,11,241.7538,0,3,2,0,1
3,3,FDQ58,7.315000,0.015388,13,155.0340,2,3,1,1,1
4,4,FDY38,12.857645,0.118599,4,234.2300,5,1,2,3,0
...,...,...,...,...,...,...,...,...,...,...,...
5676,5676,FDB58,10.500000,0.013496,13,141.3154,8,2,0,1,0
5677,5677,FDD47,7.600000,0.142991,15,169.1448,3,1,2,2,0
5678,5678,NCO17,10.000000,0.073529,8,118.7440,7,3,1,1,1
5679,5679,FDJ26,15.300000,0.000000,3,214.6218,2,3,1,1,0
5680,5680,FDU37,9.500000,0.104720,3,79.7960,7,3,1,1,0

In [95]:
test_X

,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,low_fat,Item_Weight_y,ans
0,0.007565,13,107.8622,9,1,0,1,1,20.750,1831.582510
7,0.038428,4,87.3198,2,3,1,1,0,8.300,1188.985640
13,0.099575,11,241.7538,0,3,2,0,1,14.600,569.225710
17,0.015388,13,155.0340,2,3,1,1,1,7.315,1919.554664
20,0.118599,4,234.2300,5,1,2,3,0,13.600,6953.621858
...,...,...,...,...,...,...,...,...,...,...
4874,0.013496,13,141.3154,8,2,0,1,0,10.500,2377.531852
3610,0.142991,15,169.1448,3,1,2,2,0,7.600,2752.816680
5314,0.073529,8,118.7440,7,3,1,1,1,10.000,1942.424894
4182,0.000000,3,214.6218,2,3,1,1,0,15.300,3913.172920
1759,0.104720,3,79.7960,7,3,1,1,0,9.500,1572.373254

Requirement already satisfied: scikit-learn in c:\users\user\anaconda3\lib\site-packages (0.22.1)
Requirement already satisfied: joblib>=0.11 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (0.14.1)
Requirement already satisfied: numpy>=1.11.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: scipy>=0.17.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.4.1)